<?php
/**
 * Created by PhpStorm.
 * User: romeo
 * Date: 25/02/19
 * Time: 15:36
 */

class BlogException extends \Prado\Exceptions\THttpException{

    public function getStatusCode()
    {
        return parent::getStatusCode(); // TODO: Change the autogenerated stub
    }
}